# Node on Ubuntu Latest

name: Node Ubuntu Latest

on:
  push:
    branches:
      - '*'

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: path before
        run: pwd
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: path after
        run: pwd
      - name: get inside repo
        run: npm install
        run: npm start
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm start

