# Node on Ubuntu Latest

name: Node Ubuntu Latest

on:
  push:
    branches:
      - '*'

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - name: Checkout Repository
        uses: actions/checkout@v2
      - run: pwd
      - name: get inside repo
#      - run: npm install
#     - run: npm start

