# Node on Ubuntu Latest

name: Node Ubuntu Latest

on:
  push:
    branches:
      - '*'

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: get inside repo
        uses: actions/Simple-node@2
      - run: npm install
      - run: npm start
# 
